[versions]
loom = "1.1.+"
loom_quiltflower = "1.8.+"
minotaur = "2.7.+"
cursegradle = "6.+"
github_release = "2.+"
machete = "2.+"
grgit = "5.0.+"

minecraft = "1.19.4"
quilt_mappings = "10"
fabric_loader = "0.14.19"
fabric_api = "0.78.0+1.19.4"
mixin_extras = "0.2.0-beta.6"
yet_another_config_lib = "2.4.2"
mod_menu = "6.2.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
mixin_extras = { module = "com.github.llamalad7.mixinextras:mixinextras-fabric", version.ref = "mixin_extras" }
yet_another_config_lib = { module = "dev.isxander:yet-another-config-lib", version.ref = "yet_another_config_lib" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
loom_quiltflower = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom_quiltflower" }

minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
cursegradle = { id = "me.hypherionmc.cursegradle", version.ref = "cursegradle" }
github_release = { id = "com.github.breadmoirai.github-release", version.ref = "github_release" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
